### ISSUE TITLE
KeyError: 0 when using playlist ab-similar-recordings patch

### ISSUE THREAD

**Issue by petitminion** [metabrainz/troi-recommendation-playground#36]
I'm not shure if this is a user error...

When I use `sudo python3 -m troi.cli playlist ab-similar-recordings -p --debug f5196e94-b4f4-49b2-9ffd-1a3ab5f292b9 grouchy`

I get 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/ddi/Moi/Scripts/server/funkwhale/troi_recommendation_system/troi-recommendation-playground/troi/cli.py", line 124, in <module>
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/ddi/Moi/Scripts/server/funkwhale/troi_recommendation_system/troi-recommendation-playground/troi/cli.py", line 54, in playlist
    pipeline = patch.create(pipelineargs)
  File "/mnt/ddi/Moi/Scripts/server/funkwhale/troi_recommendation_system/troi-recommendation-playground/troi/patches/ab_similar_recordings.py", line 41, in create
    recording_id = inputs[0]
KeyError: 0
```

**Comment by petitminion** [comment]
thx for the quick fix ! :)
